apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: docker-test-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.17, pipelines.kubeflow.org/pipeline_compilation_time: '2022-12-22T17:53:41.880386',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Applies Decision Tree
      and Logistic Regression for classification problem.", "name": "Docker test"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.17}
spec:
  entrypoint: docker-test
  templates:
  - name: docker-test
    dag:
      tasks:
      - {name: download-data-function, template: download-data-function}
      - name: modelbuild-data-function
        template: modelbuild-data-function
        dependencies: [reshape-data-function]
      - name: reshape-data-function
        template: reshape-data-function
        dependencies: [download-data-function]
  - name: download-data-function
    container:
      args: []
      command: [python, getdata.py]
      image: praju/kfp:getdatav2
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.17
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "Download
          dataset from minio", "implementation": {"container": {"command": ["python",
          "getdata.py"], "image": "praju/kfp:getdatav2"}}, "name": "Download Data
          Function"}', pipelines.kubeflow.org/component_ref: '{"digest": "c40507e1d468d54ee8a70bd3c9e4ff5d68a5c6c572b5943637271ae202a6af55",
          "url": "getdata/getdata.yaml"}'}
  - name: modelbuild-data-function
    container:
      args: []
      command: [python, modelbuild.py]
      image: praju/kfp:modelbuildv2
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.17
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "Building
          model and uploading it to minio", "implementation": {"container": {"command":
          ["python", "modelbuild.py"], "image": "praju/kfp:modelbuildv2"}}, "name":
          "ModelBuild Data Function"}', pipelines.kubeflow.org/component_ref: '{"digest":
          "787ca4bac7557905c60af4246abbcd50a8d9cbb89ece15a2e00718c0a2992364", "url":
          "modelbuilding/modelbuilding.yaml"}'}
  - name: reshape-data-function
    container:
      args: []
      command: [python, reshape.py]
      image: praju/kfp:reshapev2
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.17
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
      annotations: {pipelines.kubeflow.org/component_spec: '{"description": "Reshape
          the data from minio", "implementation": {"container": {"command": ["python",
          "reshape.py"], "image": "praju/kfp:reshapev2"}}, "name": "Reshape Data Function"}',
        pipelines.kubeflow.org/component_ref: '{"digest": "930e3fdf2476093f564a3b035fdac77b7830e45c0c5652a559b7917c3489222c",
          "url": "reshapedata/reshapedata.yaml"}'}
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
